"""
Master Audit Runner: Executes the 5-Tier Verification Gates and compiles
publication-grade audit reports in JSON and Markdown formats.
"""

import os
import json
from typing import Dict, Any, List
from datetime import datetime

from .gate1_search_flow import Gate1SearchFlow
from .gate2_evidence_provenance import Gate2EvidenceProvenance
from .gate3_statistics import Gate3Statistics
from .gate4_figure_vector import Gate4FigureVector
from .gate5_office_audit import Gate5OfficeAudit


class VerificationReport:
    """Represents the structured verification audit outcome."""

    def __init__(self, project_dir: str):
        self.project_dir = project_dir
        self.timestamp = datetime.now().isoformat()
        self.overall_passed = False
        self.gates: Dict[str, Dict[str, Any]] = {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "project_directory": self.project_dir,
            "timestamp": self.timestamp,
            "overall_passed": self.overall_passed,
            "gates": self.gates
        }

    def to_markdown(self) -> str:
        status_symbol = "✅ PASSED (100% Verified)" if self.overall_passed else "❌ FAILED (Discrepancies Detected)"
        lines = [
            "# 5-Tier Verification Audit Report",
            f"\n**Project Directory**: `{self.project_dir}`  ",
            f"**Audit Timestamp**: `{self.timestamp}`  ",
            f"**Overall Compliance Status**: **{status_symbol}**\n",
            "---",
            "\n## Gate-by-Gate Verification Summary\n",
            "| Gate | Description | Status | Errors / Violations |",
            "|---|---|---|---|"
        ]

        for gate_key, gate_info in self.gates.items():
            st = "✅ PASS" if gate_info.get("passed", False) else "❌ FAIL"
            errs = gate_info.get("errors", [])
            err_text = "<br>".join(errs) if errs else "Zero discrepancies."
            name = gate_info.get("name", gate_key)
            lines.append(f"| **{gate_key.upper()}** | {name} | {st} | {err_text} |")

        lines.append("\n---\n")
        lines.append("## Detailed Gate Metrics\n")

        for gate_key, gate_info in self.gates.items():
            lines.append(f"### {gate_key.upper()}: {gate_info.get('name', gate_key)}")
            lines.append(f"- **Status**: {'PASSED' if gate_info.get('passed', False) else 'FAILED'}")
            metrics = gate_info.get("metrics", {})
            if metrics:
                lines.append("- **Metrics**:")
                for k, v in metrics.items():
                    lines.append(f"  - `{k}`: {v}")
            errors = gate_info.get("errors", [])
            if errors:
                lines.append("- **Violations Detected**:")
                for e in errors:
                    lines.append(f"  - ⚠️ {e}")
            lines.append("")

        lines.append("---")
        lines.append("\n*Report generated by `sci-nma-agent` Verification Engine.*")
        return "\n".join(lines)


class AuditRunner:
    """Orchestrator for executing all 5 Verification Gates."""

    def __init__(self, project_dir: str):
        self.project_dir = project_dir

    def run_full_audit(self) -> VerificationReport:
        report = VerificationReport(self.project_dir)
        all_passed = True

        # Gate 1: PRISMA flow & Search Syntax
        g1_data_path = os.path.join(self.project_dir, "data", "prisma_flow_data.json")
        if os.path.exists(g1_data_path):
            try:
                with open(g1_data_path, "r", encoding="utf-8") as f:
                    flow_data = json.load(f)
                p1, errs1, m1 = Gate1SearchFlow.validate_prisma_flow(flow_data)
            except Exception as e:
                p1, errs1, m1 = False, [f"Gate 1 failed reading JSON: {str(e)}"], {}
        else:
            p1, errs1, m1 = False, [f"Missing PRISMA flow file: {g1_data_path}"], {}

        report.gates["gate1"] = {
            "name": "Search & PRISMA Mathematical Flow Conservation",
            "passed": p1,
            "errors": errs1,
            "metrics": m1
        }
        if not p1:
            all_passed = False

        # Gate 2: Evidence Provenance & DOI Anchoring
        g2_data_path = os.path.join(self.project_dir, "data", "extraction_dataset.json")
        if os.path.exists(g2_data_path):
            try:
                with open(g2_data_path, "r", encoding="utf-8") as f:
                    dataset = json.load(f)
                p2, errs2, m2 = Gate2EvidenceProvenance.audit_dataset_provenance(dataset)
            except Exception as e:
                p2, errs2, m2 = False, [f"Gate 2 failed reading extraction dataset: {str(e)}"], {}
        else:
            p2, errs2, m2 = False, [f"Missing extraction dataset: {g2_data_path}"], {}

        report.gates["gate2"] = {
            "name": "Evidence Authenticity & Coordinate Provenance",
            "passed": p2,
            "errors": errs2,
            "metrics": m2
        }
        if not p2:
            all_passed = False

        # Gate 3: Statistical Consistency
        if os.path.exists(g2_data_path):
            try:
                with open(g2_data_path, "r", encoding="utf-8") as f:
                    dataset = json.load(f)
                p3, errs3, m3 = Gate3Statistics.audit_dataset_statistics(dataset)
            except Exception as e:
                p3, errs3, m3 = False, [f"Gate 3 failed processing stats: {str(e)}"], {}
        else:
            p3, errs3, m3 = False, [f"Missing dataset for Gate 3 audit"], {}

        report.gates["gate3"] = {
            "name": "Numerical & Statistical Consistency",
            "passed": p3,
            "errors": errs3,
            "metrics": m3
        }
        if not p3:
            all_passed = False

        # Gate 4: Zero-Raster Vector Graphics & Multi-Format Figures
        figures_dir = os.path.join(self.project_dir, "figures")
        vector_svg_dir = os.path.join(self.project_dir, "editable_files", "vector_svg")
        target_fig_dir = vector_svg_dir if os.path.exists(vector_svg_dir) else figures_dir
        p4, errs4, m4 = Gate4FigureVector.audit_figures_directory(target_fig_dir)

        report.gates["gate4"] = {
            "name": "Zero-Raster Vector Graphics & Anti-Collision",
            "passed": p4,
            "errors": errs4,
            "metrics": m4
        }
        if not p4:
            all_passed = False

        # Gate 5: Office Suite XML Engineering & Traceable Master Database
        g5_errors = []
        g5_metrics = {}

        office_dir = os.path.join(self.project_dir, "editable_files", "office_docs")
        docx_files = [f for f in os.listdir(office_dir) if f.endswith(".docx")] if os.path.exists(office_dir) else []
        xlsx_files = [f for f in os.listdir(office_dir) if f.endswith(".xlsx")] if os.path.exists(office_dir) else []

        docx_ok = False
        if docx_files:
            p_d, e_d, m_d = Gate5OfficeAudit.audit_docx_file(os.path.join(office_dir, docx_files[0]))
            docx_ok = p_d
            g5_errors.extend(e_d)
            g5_metrics.update({"docx": m_d})
        else:
            g5_errors.append("No Word .docx files found in office_docs directory.")

        xlsx_ok = False
        if xlsx_files:
            p_x, e_x, m_x = Gate5OfficeAudit.audit_excel_file(os.path.join(office_dir, xlsx_files[0]))
            xlsx_ok = p_x
            g5_errors.extend(e_x)
            g5_metrics.update({"xlsx": m_x})
        else:
            g5_errors.append("No Master Excel .xlsx files found in office_docs directory.")

        p5 = docx_ok and xlsx_ok and (len(g5_errors) == 0)
        report.gates["gate5"] = {
            "name": "Office Suite XML Engineering & Master Database",
            "passed": p5,
            "errors": g5_errors,
            "metrics": g5_metrics
        }
        if not p5:
            all_passed = False

        report.overall_passed = all_passed
        return report

    def save_reports(self, report: VerificationReport, output_dir: str = None) -> Tuple[str, str]:
        if output_dir is None:
            output_dir = os.path.join(self.project_dir, "verification")
        os.makedirs(output_dir, exist_ok=True)

        json_path = os.path.join(output_dir, "verification_audit_report.json")
        md_path = os.path.join(output_dir, "verification_audit_report.md")

        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(report.to_dict(), f, indent=2, ensure_ascii=False)

        with open(md_path, "w", encoding="utf-8") as f:
            f.write(report.to_markdown())

        return json_path, md_path
